resolver: lts-9.0
extra-deps:
- mtlparse-0.1.4.0
- pipes-http-1.0.5
- regexpr-0.5.4
- flippers-1.0.1@sha256:e908ada5c891a6ac39cefb7e41648606d1a5f1b1048281f93bd496c5f22d73b4

# Override default flag values for local packages and extra-deps
flags: {}
